"""Bakes the live dashboard (served by dev/local_server.py) into a static,
self-contained bundle for free static hosting (Cloudflare/GitHub/Netlify
Pages) -- see docs/decisions.md, "Static deploy". The output directory
(`Chronos Orbital Conjunction System/static-build/`) is a build artifact,
not source -- it's gitignored and regenerated by this script, not hand-edited.

Usage (with dev/local_server.py already running on port 8787):

    python dev/build_static.py

Then deploy the output directory with whichever static host you're using,
e.g.:

    npx wrangler pages deploy "Chronos Orbital Conjunction System/static-build" \\
        --project-name=chronos-dashboard --force
"""
from __future__ import annotations

import json
import shutil
import sys
import urllib.request
from pathlib import Path

LOCAL_SERVER = "http://localhost:8787"
MOCKUP_DIR = Path(__file__).resolve().parent.parent / "Chronos Orbital Conjunction System"
SOURCE_HTML = MOCKUP_DIR / "Chronos Console.dc.html"
OUT_DIR = MOCKUP_DIR / "static-build"

# Each (old, new) pair converts the live-fetching dashboard into a static
# one that reads baked JSON files instead of hitting dev/local_server.py.
# Kept as explicit string substitutions (not a templating flag baked into
# the main file) so the live dev version has zero static-mode branching to
# reason about -- these two files are allowed to diverge slightly, on purpose.
REPLACEMENTS: list[tuple[str, str]] = [
    (
        '''<span style="font-size:8px;letter-spacing:1.4px;color:#5f6b7d;font-weight:600;">NEXT RUN</span>
        <span style="font-size:14px;color:#35c9d6;font-weight:600;margin-top:3px;letter-spacing:.5px;">{{ nextRun }}</span>''',
        '''<span style="font-size:8px;letter-spacing:1.4px;color:#5f6b7d;font-weight:600;">MODE</span>
        <span style="font-size:14px;color:#ffcf3a;font-weight:600;margin-top:3px;letter-spacing:.5px;">STATIC SNAPSHOT</span>''',
    ),
    (
        '''this.API_BASE = (typeof window!=='undefined' && window.CHRONOS_API_BASE) || 'http://localhost:8787';''',
        '''// Static-snapshot build: real data, baked from a live Chronos run into
    // static JSON files sitting next to this HTML (no backend, no live
    // position refresh, no custom-TLE endpoint). See docs/decisions.md,
    // "Static deploy" -- generated for a quick, 100%-free, no-server-to-run
    // share; the full live version is dev/local_server.py.
    this.STATIC_CONJ_URL = './conjunctions.json';
    this.STATIC_SNAPSHOT_URL = './catalog-snapshot.json';''',
    ),
    (
        '''this.posTimer = setInterval(()=>this.refreshPositions(), 5000);''',
        '''// No posTimer here -- static files don't have live positions to
    // refresh; the globe renders the one real snapshot baked at deploy time.''',
    ),
    ('''    clearInterval(this.posTimer);\n''', ''),
    (
        '''fetch(this.API_BASE+'/conjunctions'),
        fetch(this.API_BASE+'/catalog-snapshot'),''',
        '''fetch(this.STATIC_CONJ_URL),
        fetch(this.STATIC_SNAPSHOT_URL),''',
    ),
    (
        '''if(!conjRes.ok) throw new Error('GET /conjunctions -> HTTP '+conjRes.status);
      if(!snapRes.ok) throw new Error('GET /catalog-snapshot -> HTTP '+snapRes.status);''',
        '''if(!conjRes.ok) throw new Error('GET '+this.STATIC_CONJ_URL+' -> HTTP '+conjRes.status);
      if(!snapRes.ok) throw new Error('GET '+this.STATIC_SNAPSHOT_URL+' -> HTTP '+snapRes.status);''',
    ),
    (
        '''  async refreshPositions(){
    // Live orbital motion: re-propagate + refetch every 5s, without
    // re-fetching the (much larger, unchanging-per-run) conjunction list.
    if(!this.state.apiRun) return;
    try{
      const res = await fetch(this.API_BASE+'/catalog-snapshot');
      if(!res.ok) return;
      const body = await res.json();
      this.setState({apiCatalogSnapshot: body.catalog_snapshot, apiPositionEpoch: body.position_epoch});
      await this.ensureGlobeMounted();
      this.updateGlobePositions(body.catalog_snapshot);
      this.updateGlobeConjunctions(this.state.apiConjunctions||[]);
    }catch(e){ /* transient fetch failure -- next 5s tick will retry */ }
  }

  // --- real WebGL globe''',
        '''  // --- real WebGL globe''',
    ),
    (
        '''// Still loading (or the local dev server at this.API_BASE isn't
      // running -- see dev/local_server.py) -- every templated field needs''',
        '''// Still loading the static JSON files -- every templated field needs''',
    ),
    (
        '''bName: error ? (error) : 'connecting to '+this.API_BASE, bNorad:'—', bType:'—', bColor:'#5f6b7d',''',
        '''bName: error ? (error) : 'fetching static snapshot…', bNorad:'—', bType:'—', bColor:'#5f6b7d',''',
    ),
]


def fetch_json(path: str) -> dict:
    with urllib.request.urlopen(f"{LOCAL_SERVER}{path}", timeout=30) as r:
        return json.load(r)


def main() -> None:
    print(f"fetching {LOCAL_SERVER}/conjunctions ...")
    conjunctions = fetch_json("/conjunctions")
    print(f"fetching {LOCAL_SERVER}/catalog-snapshot ...")
    snapshot = fetch_json("/catalog-snapshot")

    OUT_DIR.mkdir(exist_ok=True)
    (OUT_DIR / "conjunctions.json").write_text(json.dumps(conjunctions))
    (OUT_DIR / "catalog-snapshot.json").write_text(json.dumps(snapshot))
    shutil.copy(MOCKUP_DIR / "support.js", OUT_DIR / "support.js")

    html = SOURCE_HTML.read_text()
    for old, new in REPLACEMENTS:
        if old not in html:
            sys.exit(
                f"build_static.py is out of sync with {SOURCE_HTML.name} -- "
                f"expected to find and replace:\n---\n{old[:200]}\n---\n"
                f"but it wasn't there verbatim. Update REPLACEMENTS to match "
                f"the current source before re-running."
            )
        html = html.replace(old, new)
    (OUT_DIR / "index.html").write_text(html)

    print(f"baked {len(conjunctions['conjunctions']):,} conjunctions, "
          f"{len(snapshot['catalog_snapshot']):,} catalog objects -> {OUT_DIR}")
    print('deploy with: npx wrangler pages deploy "Chronos Orbital Conjunction System/static-build" '
          '--project-name=chronos-dashboard --force')


if __name__ == "__main__":
    main()
